### ISSUE TITLE
Karma tests fail when linking npm modules

### ISSUE THREAD

**Issue by mayacoda** [rabix/cottontail-frontend#15]
If cwl-ts is linked, `npm test` fails with the following error:

``` bash
 Error: Cannot find module "./CommandInputParameterModel"
  at /path/to/frontend/config/spec-bundle.js:72630 <- webpack:///path/to/cwl-ts/src/models/d2sb/index.ts:2:0
```

It seems `cottontail-frontend` is looking for webpack loaders in the cwl-ts directory, instead of in the root. This has been fixed for regular dev, but it doesn't appear to work for tests.

This is in `webpack.common.js`:

``` javascript
    resolveLoader: {
        root: helpers.root("node_modules"),

        fallback: [helpers.root("node_modules")]
    }
```

**Comment by matesk8** [comment]
This is issue documented here, but the proposed solution dosen't seem to work:
https://webpack.github.io/docs/troubleshooting.html
