### ISSUE TITLE
yarn install fails with incompatible module error

### ISSUE THREAD

**Issue by oneillkza** [rabix/cottontail-frontend#88]
When I run yarn install on a clean clone of the codebase, I get the following:

```
yarn install v0.23.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error @angular/cli@1.0.0: The engine "node" is incompatible with this module. Expected version ">= 6.9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I'm running Ubuntu Xenial.

**Comment by mayacoda** [comment]
Are you sure you have the correct version of node?

**Comment by oneillkza** [comment]
No.

Longer answer: What is node, how do I determine the version, how do I determine whether it is correct, and how do I make it correct if it is not?

**Comment by mayacoda** [comment]
[Node](https://nodejs.org/en/) is a JavaScript runtime, it's one of the dependencies for running the Rabix Composer. Installing v6.10.2 LTS should do the trick.

Sorry for the unclear readme, could have sworn we had a list of dependencies/prerequisites. Thanks for bringing our attention to it, we'll update it.

**Comment by oneillkza** [comment]
Thanks! I've updated Node via the instructions [here](https://nodejs.org/en/download/package-manager/), and it seems to have installed and built succesfully!
